### ISSUE TITLE
The Creation Kit is consuming 2 GB of RAM

### ISSUE THREAD

**Issue by TheLovelyServine** [Perchik71/Creation-Kit-Platform-Extended#22]
I think I found the problem, the CK is now consuming most of my RAM and just locks up randomly and freezes, and I have to close it with task manager. What could be causing this? I don't know why it's eating up my RAM unlike before, but ever since I installed the latest version, I have been dealing with random freezes in the Creation Kit when it gets above 1.5 GB of RAM usage, even when doing something as simple as highlighting an asset. I hope this gets fixed because this is extremely annoying.

**Comment by Perchik71** [comment]
I do not know which version you are using, CKPE increases the amount of consumption, about 30% goes to the cache. To make the memory work faster. This is how the memory manager works. Something had to be sacrificed. The mod is primarily aimed at performance. This will not be fixed, as it is a technological feature. The recommended memory size is 8 GB. In general, this volume has already gone out of office use. 

If you somehow have ideas on how to make malloc spend about a second of time in 10 million iterations, we can even discuss this using modern AVX2 instructions. Then I am ready to participate in bringing this idea to life.

**Comment by Perchik71** [comment]
I'll close it for now

**Comment by ja231c** [comment]
To put it into perspective: 2GBs of RAM has been a minimum system requirement for 64-bit Windows since Windows 7, which released in 2009.

Skyrim Special Edition and Skyrim Special Edition Creation Kit both list 8GB as minimum.

It is a miracle you have even been able to run the game or CK with 2GBs at all.

I hate to say this, but it might be time for you to upgrade.
