### ISSUE TITLE
Crash with the quest window.

### ISSUE THREAD

**Issue by robertgk2017** [Perchik71/Creation-Kit-Platform-Extended#44]
Appears to be a concrete reproducible crash when you create a new quest in the ck, without hitting ok to confirm all the data

1. Create New Quest
2. Without clicking OK to save the quest, go to that quests's Aalias tab and make a new ref alias.
3. Without clicking OK to save the quest, open that ref alias and attach a script to them. (Try DefaultSetStageOnDeathRefAlias)
4. Open that new script's properties window.
5. Click OK to save the quest

Seems like its crashing because the quest itself doesn't have a script yet and it just tried to attach a script to an alias that doesn't exist.

Can also cause the crash to occur if you try to attach a script to the quest itself, without clicking OK to save the quest.

[CreationKit.exe_20240510_170618.zip](https://github.com/Perchik71/Creation-Kit-Platform-Extended/files/15282606/CreationKit.exe_20240510_170618.zip)
[CreationKit.exe_20240510_165519.zip](https://github.com/Perchik71/Creation-Kit-Platform-Extended/files/15282607/CreationKit.exe_20240510_165519.zip)

**Comment by Perchik71** [comment]
Who does that? You don't have a Form. You are trying to edit something that is not there. The quest form is created in two stages.
It's just a deliberate killing of the process. I would forbid doing anything at all without create. 
Any communication with the form occurs through a temporary form. So that you can click cancel.
