### ISSUE TITLE
Starfield CK Dark Mode Conflicts with CKPE Dark Mode

### ISSUE THREAD

**Issue by yak3d** [Perchik71/Creation-Kit-Platform-Extended#55]
When using the built-in Plastique (dark) theme in the Starfield CreationKit, the toolbar + menubar are correctly dark themed, however the font color for the listview uses black as the text color which makes it hard to read.

![image](https://github.com/user-attachments/assets/539c50c4-7ea8-4b76-b204-f5e9d54b609e)

If you change the built-in theme to Windows (default), the menu bar/tool bar are light themed but the text becomes readable.

![image](https://github.com/user-attachments/assets/ba4bfa83-022c-49b7-bff9-09d4ef5df45b)

Happy to contribute to fix but wasn't sure where to start.

**Comment by Perchik71** [comment]
I am aware of this problem, Bethesda has created new dialogues using Qt, and also replaced the main one. Qt does not use standard Windows classes, it draws everything by itself, which makes the application so bold. I am considering merging, as it makes the task easier, and so far the problem is only with the ListView text.

**Comment by yak3d** [comment]
> I am aware of this problem, Bethesda has created new dialogues using Qt, and also replaced the main one. Qt does not use standard Windows classes, it draws everything by itself, which makes the application so bold. I am considering merging, as it makes the task easier, and so far the problem is only with the ListView text.
> 
> Edit: Somehow, Qt intercepts the rendering of text on itself, this should be prohibited. But I'll think about it later. I'll be glad if someone finds a way to fix this while I'm developing general patches.

I can take a look, never worked on this stuff before but worth a shot.

**Comment by yak3d** [comment]
For what its worth, I did take a look but I think I'm out of depth here lol.

**Comment by yak3d** [comment]
@Perchik71  Okay I did look into it and seemingly got it working though I'm a little suspect on the fix.

![image](https://github.com/user-attachments/assets/7209f85d-b151-4814-a53b-a35094028902)
![image](https://github.com/user-attachments/assets/c294b085-24a4-465b-aa0b-cc90cf5729e1)

https://github.com/Perchik71/Creation-Kit-Platform-Extended/commit/1f6168a0a762d181e599ccccd874e7b4abf2cd27

**Comment by Perchik71** [comment]
@yak3d 
looks like problem is exactly here, since there are three listviews whose text does not change, and the system is sent.
need to find a suitable solution for all versions of CK. 
https://github.com/Perchik71/Creation-Kit-Platform-Extended/blob/185f16e4196734905bc961522bdb7e784b2cffaa/Creation%20Kit%20Platform%20Extended%20Core/UITheme/ListView.cpp#L210

**Comment by Perchik71** [comment]
![2024-09-14_13-57-29](https://github.com/user-attachments/assets/88c0f9d2-39f0-44a2-b2c7-23324f0062a0)
