### ISSUE TITLE
When trying to upload to PS4, vanilla assets get falsely flagged as custom.

### ISSUE THREAD

**Issue by TheLovelyServine** [Perchik71/Creation-Kit-Platform-Extended#7]
The CK gives you an error, "Playstation does not support archives." It's annoying because it falsely flags vanilla assets as custom, and I have to rename the textures and meshes folders and restart the CK, the error needs to be removed for the uploader's convenience. I am not trying to upload custom stuff to PS4, the CK just falsely flags vanilla assets as custom and it's really irritating and inconvenient. It would help the PS4 modding community so much if this false flagging error was gone as we are just trying to upload our ESPs. I'm doing this on the most recent version of the CK.

**Comment by Perchik71** [comment]
I looked at it all. In general, user data is collected first, namely which platform you are going to ship to. Since Bethesda has added multiple uploads to its servers, they have only one data list. I can provide that if you ship to PS4, then block all other platforms and exclude their uploads, and in one function, which I suspect is responsible for collecting and analyzing the mod, block and as a result there will be only one file. The ESP itself.

**Comment by TheLovelyServine** [comment]
Ah, so are you working on a fix for that, by chance?

**Comment by Perchik71** [comment]
Before you do anything, need to think about it. I don't see the point in dividing the upload into platforms in two stages. I'll make a check mark that will exclude the analysis altogether. I think this is a simple and feasible solution to this problem. I'll just test it on a fake connection, since I don't have an account and I don't want to put my mods there, I'll drop the finished version here, and you try it out on the real one.

**Comment by TheLovelyServine** [comment]
Ah ok

**Comment by Perchik71** [comment]
You can try it, download the latest pre-release version 0.2 build 159.
![2024-01-19_21-38-08](https://github.com/Perchik71/Creation-Kit-Platform-Extended/assets/13632112/a15eda1f-5d80-438b-b775-69226f3d1a79)
I changed the behavior of this dialog, it seems, I took into account all possible assumptions of an inexperienced user. So just turn it on and try.

**Comment by TheLovelyServine** [comment]
Ok, will do.

**Comment by TheLovelyServine** [comment]
I just tested it, and it works!

**Comment by Perchik71** [comment]
Nice!
